### ISSUE TITLE
Applying critical errata sometimes fails

### ISSUE THREAD

**Issue by jayhendren** [chef-partners/redhat-subscription-manager-cookbook#16]
The resource `rhsm_errata_level 'critical'` sometimes fails on RHEL 7 for no apparent reason. The error doesn't seem to be deterministic; re-running chef-client or destroying the test vm, unregistering it from satellite, and spinning up a new test vm fails to reproduce the error.  Logging into the node and manually running `yum update --sec-severity=Critical -y` also fails to produce any error.

```
         * rhsm_errata_level[critical] action install
        (skipped due to only_if)
           * execute[Install any critical errata] action run

             ================================================================================
             Error executing action `run` on resource 'execute[Install any critical errata]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received ''
             ---- Begin output of yum update --sec-severity=Critical -y ----
             STDOUT: Loaded plugins: package_upload, product-id, search-disabled-repos, subscription-
                    : manager
             STDERR: 
             ---- End output of yum update --sec-severity=Critical -y ----
             Ran yum update --sec-severity=Critical -y returned 

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_errata_level.rb

       34:       execute "Install any #{errata_level} errata" do
       35:         command "yum update --sec-severity=#{errata_level.capitalize} -y"
       36:         action :run
       37:       end
       38:     end

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_errata_level.rb:34:in `block in <class:RhsmErrataLevel>'

             execute("Install any critical errata") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "yum update --sec-severity=Critical -y"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "cub_redhat_subscription_manager"
             end


           ================================================================================
           Error executing action `install` on resource 'rhsm_errata_level[critical]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[Install any critical errata] (/tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_errata_level.rb line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
           ---- Begin output of yum update --sec-severity=Critical -y ----
           STDOUT: Loaded plugins: package_upload, product-id, search-disabled-repos, subscription-
                  : manager
           STDERR: 
           ---- End output of yum update --sec-severity=Critical -y ----
           Ran yum update --sec-severity=Critical -y returned 

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cub_redhat_subscription_manager/recipes/unixops.rb

            22: rhsm_errata_level node['rhsm']['rhsm_errata_level']

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cub_redhat_subscription_manager/recipes/unixops.rb:22:in `from_file'

           rhsm_errata_level("critical") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :rhsm_errata_level
             cookbook_name "cub_redhat_subscription_manager"
             recipe_name "unixops"
             errata_level "critical"
       end


       Running handlers:
       [2016-02-16T13:09:09-07:00] ERROR: Running exception handlers
         - MailHandler
       Running handlers complete
       [2016-02-16T13:09:27-07:00] ERROR: Exception handlers complete
       Chef Client failed. 7 resources updated in 02 minutes 43 seconds
       [2016-02-16T13:09:27-07:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-16T13:09:27-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-16T13:09:27-07:00] ERROR: rhsm_errata_level[critical] (cub_redhat_subscription_manager::unixops line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[Install any critical errata] (/tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_errata_level.rb line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
       ---- Begin output of yum update --sec-severity=Critical -y ----
       STDOUT: Loaded plugins: package_upload, product-id, search-disabled-repos, subscription-
              : manager
       STDERR: 
       ---- End output of yum update --sec-severity=Critical -y ----
       Ran yum update --sec-severity=Critical -y returned 
       [2016-02-16T13:09:35-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by adamleff** [comment]
This error indicates that the actual execution of the `yum` command returned a non-zero exit code. This is unfortunately outside of Chef's control. The error appearing to be non-deterministic or non-predictable is likely an environment issue, such as the mirror your machine is trying to use is unreachable or inconsistently reachable due to a network issue, for example. Unfortunately, we're not seeing anything on STDERR which is hampering your ability to know with 100% certainty what the issue is.

In your recipe, you can try and increase the retries on this resource in an effort to work around the environmental issue you're experiencing:

```
rhsm_errata_level 'critical' do
  retries 3
end
```

This will instruct Chef to catch any exceptions and retry the resource up to 3 times before failing the chef-client run.

I hope this helps!

**Comment by jayhendren** [comment]
Thanks, I will try adding the `retries` attribute to the resource to see if it helps.

I assumed this was a bug on the Chef side of things due to 1) I could not reproduce the issue by running a yum update manually; 2) It's not apparent that yum actually ran into an error, since there's no useful information on either std out or std err; 3) Chef reports `Expected process to exit with [0], but received ''` instead of `...received '1'` or a similar message indicating the actual exit code of the command.
