### ISSUE TITLE
register_rhel fails with deprecation notice

### ISSUE THREAD

**Issue by roberto-mardeni** [chef-partners/redhat-subscription-manager-cookbook#29]
I get the following error when using the rhel_register resource:

```
       Recipe: ipc_linux::register_rhel
         * rhsm_register[default-centos-67.vagrantup.com] action register[2017-09-13T15:29:01+00:00] ERROR: rename satellite_host to new_resource.satellite_host (CHEF-19)/tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_register.rb:39:in `block (2 levels) in <class:RhsmRegister>'.
       Please see https://docs.chef.io/deprecations_namespace_collisions.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/formatters/doc.rb:419:in `deprecation'
       [2017-09-13T15:29:01+00:00] ERROR: rename satellite_host to new_resource.satellite_host (CHEF-19)/tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_register.rb:39:in `block (2 levels) in <class:RhsmRegister>'.
       Please see https://docs.chef.io/deprecations_namespace_collisions.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/formatters/doc.rb:419:in `deprecation'


           ================================================================================
           Error executing action `register` on resource 'rhsm_register[default-centos-67.vagrantup.com]'
           ================================================================================

           Chef::Exceptions::DeprecatedFeatureError
           ----------------------------------------
           "rename satellite_host to new_resource.satellite_host (CHEF-19)/tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_register.rb:39:in `block (2 levels) in <class:RhsmRegister>'.\nPlease see https://docs.chef.io/deprecations_namespace_collisions.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/formatters/doc.rb:419:in `deprecation'"

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_register.rb:39:in `block (2 levels) in <class:RhsmRegister>'
           /tmp/kitchen/cache/cookbooks/redhat_subscription_manager/libraries/rhsm_register.rb:38:in `block in <class:RhsmRegister>'

           Resource Declaration:
           ---------------------
           suppressed sensitive resource output

           Compiled Resource:
           ------------------
           suppressed sensitive resource output

           System Info:
           ------------
           chef_version=13.4.19
           platform=centos
           platform_version=6.7
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=6533;start=15:28:59;
           executable=/opt/chef/bin/chef-client

```

**Comment by tas50** [comment]
This is fixed in the latest release
